# Generated by Django 5.0.6 on 2024-06-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_x_networkcoverage_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkcoverage',
            old_name='lat',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='networkcoverage',
            old_name='long',
            new_name='y',
        ),
    ]
