# Generated by Django 5.0.6 on 2024-06-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_networkcoverage_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkcoverage',
            old_name='x',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='networkcoverage',
            old_name='y',
            new_name='long',
        ),
    ]
